const {
  VITE_EDDIE_PUBLIC_URL,
  VITE_EDDIE_ADMIN_CONSOLE_URL,
  VITE_EDDIE_MANAGEMENT_URL,
  VITE_EDDIE_MANAGEMENT_URL_PREFIX
} = import.meta.env

const CORE_URL = THYMELEAF_EDDIE_PUBLIC_URL ?? VITE_EDDIE_PUBLIC_URL
const ADMIN_URL = THYMELEAF_EDDIE_ADMIN_CONSOLE_URL ?? VITE_EDDIE_ADMIN_CONSOLE_URL
const MANAGEMENT_URL = THYMELEAF_EDDIE_MANAGEMENT_URL ?? VITE_EDDIE_MANAGEMENT_URL
const MANAGEMENT_URL_PREFIX =
  THYMELEAF_EDDIE_MANAGEMENT_URL_PREFIX ?? VITE_EDDIE_MANAGEMENT_URL_PREFIX

export const CSRF_HEADER = THYMELEAF_CSRF_HEADER
export const CSRF_TOKEN = THYMELEAF_CSRF_TOKEN

export const PERMISSIONS_API_URL = `${ADMIN_URL}/statusMessages`
export const TERMINATION_API_URL = `${ADMIN_URL}/terminate`
export const REGION_CONNECTOR_API_URL = `${CORE_URL}/api/region-connectors-metadata`
export const REGION_CONNECTOR_HEALTH_API_URL = `${CORE_URL}/actuator/health`
export const REGION_CONNECTORS_SUPPORTED_FEATURES_API_URL = `${MANAGEMENT_URL}/${MANAGEMENT_URL_PREFIX}/region-connectors/supported-features`
export const REGION_CONNECTORS_SUPPORTED_DATA_NEEDS_API_URL = `${MANAGEMENT_URL}/${MANAGEMENT_URL_PREFIX}/region-connectors/supported-data-needs`
export const DATA_NEEDS_API_URL = `${MANAGEMENT_URL}/data-needs/${MANAGEMENT_URL_PREFIX}`
