openapi: 3.0.1
info:
  title: Data needs public API
  description: Used by the frontend to get information about data needs.
  version: 1.0.0

servers:
  - url: http://localhost:8080/data-needs
    description: Local development server

tags:
  - name: DataNeeds

paths:
  /api:
    get:
      operationId: getDataNeedIdsAndNames
      tags:
        - DataNeeds
      summary: Get a list of IDs and names of all data needs
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataNeedsNameAndIdProjection'
              examples:
                example:
                  value:
                    - id: 207defb8-3aad-4281-a6ef-d77ba1601217
                      name: My awesome data need
                    - id: my-id
                      name: Another data need

  /api/{id}:
    get:
      operationId: getDataNeed
      tags:
        - DataNeeds
      summary: Get details of an existing data need
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 7f57cf16-5121-42a6-919e-7f7335826e64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataNeed'
              examples:
                example:
                  value:
                    type: validated
                    id: d73f44e1-239c-4610-b1e4-212ae35a792e
                    name: My awesome data need
                    description: descr
                    purpose: purpose
                    policyLink: https://example.com/toc
                    createdAt: '2024-03-14T06:16:49.983259Z'
                    duration:
                      type: relativeDuration
                      start: P-1Y
                      end: P12M
                    energyType: ELECTRICITY
                    minGranularity: PT15M
                    maxGranularity: PT15M

        '404':
          description: No data need with the supplied id was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EddieApiError'
              examples:
                example:
                  value:
                    errors:
                      - message: No data need with ID '7f57cf16-5121-42a6-919e-7f7335826e64' found.

components:
  schemas:
    DataNeedsNameAndIdProjection:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string

    DataNeed:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        description:
          type: string
        purpose:
          type: string
        policyLink:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
          readOnly: true
        enabled:
          type: boolean
        type:
          type: string
        regionConnectorFilter:
          $ref: '#/components/schemas/RegionConnectorFilter'

    RegionConnectorFilter:
      type: object
      required:
        - type
        - regionConnectorIds
      properties:
        type:
          type: string
          enum: [ blocklist, allowlist ]
        regionConnectorIds:
          type: array
          items:
            type: string

    EddieApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
