ALTER TABLE permission
    DROP CONSTRAINT permission_status_check;

UPDATE permission
SET status ='FULFILLED'
WHERE status = 'TIME_LIMIT';

ALTER TABLE permission
    ADD CONSTRAINT permission_status_check
        CHECK ((status)::TEXT = ANY
               ((ARRAY ['ACCEPTED'::CHARACTER VARYING, 'WAITING_FOR_START'::CHARACTER VARYING, 'STREAMING_DATA'::CHARACTER VARYING, 'REJECTED'::CHARACTER VARYING, 'REVOCATION_RECEIVED'::CHARACTER VARYING, 'REVOKED'::CHARACTER VARYING, 'TERMINATED'::CHARACTER VARYING, 'FULFILLED'::CHARACTER VARYING])::TEXT[]));