DROP TABLE IF EXISTS aiida_record;

CREATE TABLE aiida_record
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    asset         TEXT,
    PRIMARY KEY (id)
);

create table aiida_record_value (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aiida_record_id         BIGINT NOT NULL,
    raw_tag                 TEXT,
    data_tag                TEXT,
    raw_value               TEXT,
    raw_unit_of_measurement TEXT,
    value                   TEXT,
    unit_of_measurement     TEXT,
    FOREIGN KEY (aiida_record_id)
        REFERENCES aiida_record (id)
);


