CREATE TABLE data_source (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    data_source_type VARCHAR(255),
    asset VARCHAR(255),
    name VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    source_type VARCHAR(255),
    mqtt_server_uri VARCHAR(255),
    mqtt_subscribe_topic VARCHAR(255),
    mqtt_username VARCHAR(50),
    mqtt_password VARCHAR(50),
    metering_id VARCHAR(50),
    simulation_period INTEGER
);