CREATE TABLE inbound_record
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    asset          TEXT,
    user_id        uuid                        NOT NULL,
    data_source_id uuid                        NOT NULL,
    payload        TEXT                        NOT NULL
);

ALTER TABLE data_source
    ADD COLUMN access_code TEXT;