--  SPDX-FileCopyrightText: 2026 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
--  SPDX-License-Identifier: Apache-2.0

-- The old table had no way to be populated before this feature, so it is safe to drop and recreate it
DROP TABLE connection_limit_default;

CREATE TABLE connection_limit_default
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id uuid        NOT NULL REFERENCES permission (permission_id),
    meter_id      TEXT        NOT NULL DEFAULT '',
    start         timestamptz NOT NULL,
    replaced_at   timestamptz NULL,
    min_limit_kw  DECIMAL     NULL,
    max_limit_kw  DECIMAL     NULL,
    CONSTRAINT connection_limit_default_valid_interval CHECK (replaced_at IS NULL OR start < replaced_at)
);

CREATE INDEX idx_connection_limit_default_permission_start
    ON connection_limit_default (permission_id, start);