## Variable for requests
@granularity = VH_kwartier_uur
@ean = 541441010000000001
@start = 2024-12-01T00:00:00Z
@end = 2024-12-19T23:59:59Z

#### Request to create a permission request
# In our case the referenceNumber is the permisisonId, so for test requests, just use a random uuid
< {%
    const shortendUUid = $uuid.replace(/-/g, "");

    console.log(shortendUUid)
    client.global.set("referenceNumber", shortendUUid)
%}
POST {{baseUrl}}//api/v2.0/shortUrlIdentifier
Authorization: Bearer {{$auth.token("fluvius")}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
  "dataAccessContractNumber": "{{contractNumber}}",
  "referenceNumber": "{{referenceNumber}}",
  "flow": "B2C",
  "dataServices": [
    {
      "dataServiceType": "{{granularity}}",
      "dataPeriodFrom": "{{start}}",
      "dataPeriodTo": "{{end}}"
    }
  ],
  "numberOfEans": "1",
  "returnUrlSuccess": null,
  "returnUrlFailed": null,
  "sso": true,
  "enterpriseNumber": null
}

#### Request to create a mock mandate
# The eanNumber is assembled, based on the required services, for more information checkout the docs
# EanNumber Assembly:
# 54144 (0 -> electricity, 1 -> gas) (0 -> decrease only, 1 -> sampling & injection) (0 -> VH_day, 1 -> VH_quarter_hour) 0000000 (xxx -> 1000 meters per group)
POST {{baseUrl}}/api/v2.0/Mandate/mock
Authorization: Bearer {{$auth.token("fluvius")}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
  "referenceNumber": "{{referenceNumber}}",
  "eanNumber": "{{ean}}",
  "dataServiceType": "{{granularity}}",
  "dataPeriodFrom": "{{start}}",
  "dataPeriodTo": "{{end}}",
  "status": "Approved",
  "mandateExpirationDate": "2024-12-29T23:00:00Z",
  "renewalStatus": "ToBeRenewed"
}

#### Request specific mandates
GET {{baseUrl}}/api/v2.0/Mandate?ReferenceNumber={{referenceNumber}}
Authorization: Bearer {{$auth.token("fluvius")}}
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

#### Request all mandates
GET {{baseUrl}}/api/v2.0/Mandate
Authorization: Bearer {{$auth.token("fluvius")}}
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

#### Request Installation
GET {{baseUrl}}/api/v2.0/Mandate/installation?referenceNumber={{referenceNumber}}&eanNumber={{ean}}
Authorization: Bearer {{$auth.token("fluvius")}}
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

### Request energy consumption data from mandate
GET {{baseUrl}}/api/v2.0/Mandate/energy?
                                referenceNumber={{referenceNumber}}&
    eanNumber={{ean}}&
    DataServiceType={{granularity}}&
                                PeriodType=readTime&
    from={{start}}&
    to={{end}}
Authorization: Bearer {{$auth.token("fluvius")}}
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

