package energy.eddie.api.agnostic.aiida;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;

import java.util.UUID;

public class QrCodePermissionDto {
    /**
     * ID of these permission as generated by this region connector. AIIDA will use the same ID.
     */
    @JsonProperty
    private final UUID permissionId;
    /**
     * Name of the service that the permission is for.
     */
    @NotBlank(message = "must not be blank")
    private final String serviceName;

    @SuppressWarnings("unused")
    private QrCodePermissionDto() {
        // for deserialization
        permissionId = UUID.randomUUID();
        serviceName = "";
    }

    public QrCodePermissionDto(UUID permissionId, String serviceName) {
        this.permissionId = permissionId;
        this.serviceName = serviceName;
    }

    public UUID permissionId() {
        return permissionId;
    }

    public String serviceName() {
        return serviceName;
    }
}