// SPDX-FileCopyrightText: 2024-2025 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
// SPDX-License-Identifier: Apache-2.0

package energy.eddie.api.agnostic.aiida;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;

import java.util.UUID;

public class QrCodeDto {
    /**
     * Token Access token to be included by AIIDA for the handshake.
     */
    @JsonProperty
    private final UUID eddieId;
    /**
     * ID of this permission as generated by this region connector. AIIDA will use the same ID.
     */
    @JsonProperty
    private final UUID permissionId;
    /**
     * Name of the service that the permission is for.
     */
    @JsonProperty
    @NotBlank(message = "must not be blank")
    private final String serviceName;
    /**
     * URL where AIIDA should send the handshake request to.
     */
    @JsonProperty
    @NotBlank(message = "must not be blank")
    private final String handshakeUrl;
    /**
     * Access token to be included by AIIDA for the handshake.
     */
    @JsonProperty("bearerToken")
    @NotBlank(message = "must not be blank")
    private final String accessToken;

    @SuppressWarnings("unused")
    private QrCodeDto() {
        // for deserialization
        eddieId = UUID.randomUUID();
        permissionId = UUID.randomUUID();
        serviceName = "";
        handshakeUrl = "";
        accessToken = "";
    }

    public QrCodeDto(UUID eddieId, UUID permissionId, String serviceName, String handshakeUrl) {
        this.eddieId = eddieId;
        this.permissionId = permissionId;
        this.serviceName = serviceName;
        this.handshakeUrl = handshakeUrl;
        // This token will be set by Jackson after deserialization
        this.accessToken = "";
    }

    public UUID eddieId() {
        return eddieId;
    }

    public UUID permissionId() {
        return permissionId;
    }

    public String serviceName() {
        return serviceName;
    }

    public String handshakeUrl() {
        return handshakeUrl;
    }

    public String accessToken() {
        return accessToken;
    }
}