package energy.eddie.api.agnostic.aiida;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;

/**
 * This data transfer object contains all necessary information that should be encoded in a QR code, that is then
 * presented to the customer.
 *
 * @param permissionId ID of this permission as generated by this region connector. AIIDA will use the same ID.
 * @param serviceName  Name of the service that the permission is for.
 * @param handshakeUrl URL where AIIDA should send the handshake request to.
 * @param accessToken  Access token to be included by AIIDA for the handshake.
 */
public record QrCodeDto(
        @JsonProperty
        @NotBlank(message = "must not be blank")
        String permissionId,
        @JsonProperty
        @NotBlank(message = "must not be blank")
        String serviceName,
        @JsonProperty
        @NotBlank(message = "must not be blank")
        String handshakeUrl,
        @JsonProperty
        @NotBlank(message = "must not be blank")
        String accessToken) {
}
