// SPDX-FileCopyrightText: 2024-2025 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
// SPDX-License-Identifier: Apache-2.0

package energy.eddie.api.agnostic.aiida;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;

import java.util.List;
import java.util.UUID;

/**
 * @param eddieId       Token Access token to be included by AIIDA for the handshake.
 * @param permissionIds ID of these permission as generated by this region connector. AIIDA will use the same ID.
 * @param handshakeUrl  URL template used by AIIDA to send the handshake request.
 *                      The placeholder {permissionId} is replaced with the actual permission ID.
 * @param accessToken   Access token to be included by AIIDA for the handshake.
 */
public record QrCodeDto(@JsonProperty UUID eddieId,
                        @JsonProperty @NotEmpty(message = "must not be empty") List<UUID> permissionIds,
                        @JsonProperty @NotBlank(message = "must not be blank") String handshakeUrl,
                        @JsonProperty @NotBlank(message = "must not be blank") String accessToken) {
    @SuppressWarnings("unused")
    private QrCodeDto() {
        // for deserialization
        this(UUID.randomUUID(), List.of(), "", "");
    }
}