### Get CDS Metadata
GET {{cds_server}}/.well-known/carbon-data-spec.json

> {%
  client.global.set("oauth_metadata", response.body.oauth_metadata)
%}

### Get OAuth metadata
GET {{oauth_metadata}}

> {%
  client.global.set("clients_endpoint", response.body.cds_clients_api)
  client.global.set("credentials_endpoint", response.body.cds_credentials_api)
%}

### Register Admin Client
POST {{cds_server}}/oauth/register
Content-Type: application/json

{
  "scope": "customer_data",
  "redirect_uris": [
    "https://localhost"
  ]
}


### GET clients
GET {{clients_endpoint}}
Authorization: Bearer {{$auth.token("cds")}}

> {%
  const body = response.body
  for (let item in body.clients) {
    item = body.clients[item]
    if (item.scope === "customer_data") {
      client.global.set("customer_client_endpoint", item.cds_client_uri)
      client.global.set("customer_client_id", item.client_id)
      client.global.set("cds_server_metadata", item.cds_server_metadata)
      break;
    }
  }
%}

### Get specific server metadata endpoint
GET {{cds_server_metadata}}
Authorization: Bearer {{$auth.token("cds")}}

> {%
  client.global.set("cds_oauth_endpoint_client_specific", response.body.oauth_metadata)
%}

### Get specific oauth metadata endpoint
GET {{cds_oauth_endpoint_client_specific}}
Authorization: Bearer {{$auth.token("cds")}}

### UPDATE client
PUT {{customer_client_endpoint}}
Authorization: Bearer {{$auth.token("cds")}}
Content-Type: application/json

{
  "redirect_uris": [
    "https://localhost"
  ]
}

### GET client credentials
GET {{credentials_endpoint}}?client_ids={{customer_client_id}}
Authorization: Bearer {{$auth.token("cds")}}

### GET usage segments
GET https://s-1cd67f6d.cds.utilityapi.com/api/customerdata/v1/usage-segments/?after=20241211&before=20250310
Authorization: Bearer {{access_token}}

###
GET {{cds_server}}/oauth/authorize/?
    client_id={{customer-data-client-id}}&
    scope=customer_data&
    redirect_uri=https://localhost&
    state={{$random.alphabetic(10)}}&
    response_type=code
Cookie: sessionid=7zl5hfj4uo3xfshn9kcu7acyojpv9t5i
