' SPDX-FileCopyrightText: 2025 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
' SPDX-License-Identifier: Apache-2.0

@startuml

participant DataSource as "Data Source"
participant Adapter as "Data Source\nAdapter"
participant Aggregator
database DB
participant Provisioner
participant Scheduler as "Permission\nScheduler"
participant Streamer
actor Client
actor EP

DataSource -> Adapter : sends data\n(over e.g. MQTT)
Adapter -> Aggregator : forwards data
Aggregator -> DB : stores data
Aggregator -> Provisioner : forwards data
Scheduler -> Streamer : creates streamers\nfor permissions
Aggregator -> Streamer : forwards filtered and processed data
Provisioner -> Client : streams data over HTTP or MQTT
Streamer <-> EP : streams data over MQTT

@enduml