@startuml
class QrCode {
   handshakeUrl: URL
   permissionId: UUID
   serviceName: String
   jwt: String
}

note "The service name is included that something like 'Loading data for <serviceName>'\ncan be shown in the AIIDA UI during the handshake" as n1
@enduml
