CREATE TABLE kafka_streaming_config
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bootstrap_servers TEXT         NOT NULL,
    data_topic        VARCHAR(255) NOT NULL,
    status_topic      VARCHAR(255) NOT NULL,
    subscribe_topic   VARCHAR(255) NOT NULL
);



CREATE TABLE permission
(
    permission_id             CHAR(36)                    NOT NULL PRIMARY KEY,
    connection_id             VARCHAR(255)                NOT NULL,
    expiration_time           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    grant_time                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoke_time               TIMESTAMP(6) WITH TIME ZONE,
    service_name              TEXT                        NOT NULL,
    start_time                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status                    VARCHAR(100)                NOT NULL
        CONSTRAINT permission_status_check
            CHECK ((status)::TEXT = ANY
                   ((ARRAY ['ACCEPTED'::CHARACTER VARYING, 'WAITING_FOR_START'::CHARACTER VARYING, 'STREAMING_DATA'::CHARACTER VARYING, 'REJECTED'::CHARACTER VARYING, 'REVOCATION_RECEIVED'::CHARACTER VARYING, 'REVOKED'::CHARACTER VARYING, 'TERMINATED'::CHARACTER VARYING, 'TIME_LIMIT'::CHARACTER VARYING])::TEXT[])),
    kafka_streaming_config_id INTEGER                     NOT NULL UNIQUE
);



CREATE TABLE permission_requested_codes
(
    permission_id CHAR(36) NOT NULL REFERENCES permission (permission_id),
    code          TEXT     NOT NULL,
    PRIMARY KEY (permission_id, code)
);



CREATE TABLE aiida_record
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    code          TEXT                        NOT NULL,
    integer_value INTEGER,
    string_value  TEXT,
    PRIMARY KEY (timestamp, id)
);

SELECT create_hypertable('aiida_record', 'timestamp', migrate_data := TRUE);