package energy.eddie.regionconnector.cds.client.responses;

public sealed interface ApiClientCreationResponse permits AuthorizationCodeGrantTypeNotSupported, CoverageNotSupportedResponse, CreatedApiClientResponse, OAuthNotSupportedResponse, RefreshTokenGrantTypeNotSupported {
}
