package energy.eddie.regionconnector.at.eda;

import at.ebutilities.schemata.customerconsent.cmrequest._01p10.CMRequest;
import at.ebutilities.schemata.customerconsent.cmrevoke._01p00.CMRevoke;
import at.ebutilities.schemata.customerprocesses.consumptionrecord._01p30.ConsumptionRecord;
import at.ebutilities.schemata.customerprocesses.masterdata._01p30.MasterData;
import energy.eddie.regionconnector.at.eda.models.CMRequestStatus;
import jakarta.xml.bind.JAXBException;
import reactor.core.publisher.Flux;


/**
 * This interface defines the methods that must be provided by classes that facilitate the communication with EDA.
 * The returned classes are part of the EDA schemas and are generated by the JAXB compiler.
 */
public interface EdaAdapter extends AutoCloseable {

    /**
     * Returns a stream of CMRequestStatus objects that describe the current permission/consent status of all sent requests.
     */
    Flux<CMRequestStatus> getCMRequestStatusStream();

    /**
     * Returns a stream of ConsumptionRecord objects tha contain information regarding energy consumption for a specific metering point.
     */
    Flux<ConsumptionRecord> getConsumptionRecordStream();

    /**
     * Returns a stream of CMRevoke objects that contain information regarding revoked permissions/consents.
     */
    Flux<CMRevoke> getCMRevokeStream();


    /**
     * Returns a stream of MasterData objects that contain information regarding metering points and their owners.
     */
    Flux<MasterData> getMasterDataStream();


    /**
     * This method sends a CMRequest to EDA. A CMRequest can be used to request either metering or master data.
     * @param request The CMRequest message that should be sent to EDA.
     * @throws TransmissionException If the request could not be sent. Reasons can be a connection error or a malformed request.
     * @throws JAXBException If the request could not be serialized.
     */
    void sendCMRequest(CMRequest request) throws TransmissionException, JAXBException;

    /**
     * This method sends a CMRevoke to EDA. A CMRevoke can be used to revoke an active permission/consent.
     * @param revoke The CMRevoke message that should be sent to EDA.
     * @throws TransmissionException If the request could not be sent. Reasons can be a connection error or a malformed request.
     * @throws JAXBException If the request could not be serialized.
     */
    void sendCMRevoke(CMRevoke revoke) throws TransmissionException, JAXBException;

    /**
     * This method starts the connection to EDA. It must be called before any of the methods that use the connection can be used.
     * @throws TransmissionException If the connection to EDA could not be established.
     */
    void start() throws TransmissionException;

}



