package energy.eddie.regionconnector.at.eda;

import energy.eddie.api.v0.HealthState;
import energy.eddie.regionconnector.at.eda.dto.EdaCMRevoke;
import energy.eddie.regionconnector.at.eda.dto.IdentifiableConsumptionRecord;
import energy.eddie.regionconnector.at.eda.dto.IdentifiableMasterData;
import energy.eddie.regionconnector.at.eda.models.CMRequestStatus;
import energy.eddie.regionconnector.at.eda.requests.CCMORequest;
import energy.eddie.regionconnector.at.eda.requests.CCMORevoke;
import reactor.core.publisher.Flux;

import java.util.Map;


/**
 * This interface defines the methods that must be provided by classes that facilitate the communication with EDA. The
 * returned classes are part of the EDA schemas and are generated by the JAXB compiler.
 */
public interface EdaAdapter extends AutoCloseable {

    /**
     * Returns a stream of CMRequestStatus objects that describe the current permission/consent status of all sent
     * requests.
     */
    Flux<CMRequestStatus> getCMRequestStatusStream();

    /**
     * Returns a stream of EdaConsumptionRecord objects tha contain information regarding energy consumption for a
     * specific metering point.
     */
    Flux<IdentifiableConsumptionRecord> getConsumptionRecordStream();

    /**
     * Returns a stream of EdaCMRevoke objects that contain information regarding revoked permissions/consents.
     */
    Flux<EdaCMRevoke> getCMRevokeStream();


    /**
     * Returns a stream of EdaMasterData objects that contain information regarding metering points and their owners.
     */
    Flux<IdentifiableMasterData> getMasterDataStream();


    /**
     * This method sends a CCMORequest to EDA. A CCORequest can be used to request either metering or master data.
     *
     * @param request The CCMORequest message that should be sent to EDA.
     * @throws TransmissionException If the request could not be sent. Reasons can be a connection error or a malformed
     *                               request.
     */
    void sendCMRequest(CCMORequest request) throws TransmissionException;

    /**
     * This method sends a CCMORevoke to EDA. A CCMORevoke can be used to revoke an active permission/consent.
     *
     * @param revoke The CCMORevoke message that should be sent to EDA.
     * @throws TransmissionException If the request could not be sent. Reasons can be a connection error or a malformed
     *                               request.
     */
    void sendCMRevoke(CCMORevoke revoke) throws TransmissionException;

    /**
     * This method starts the connection to EDA. It must be called before any of the methods that use the connection can
     * be used.
     *
     * @throws TransmissionException If the connection to EDA could not be established.
     */
    void start() throws TransmissionException;

    Map<String, HealthState> health();
}
