package energy.eddie.aiida.datasources.sga;

import energy.eddie.aiida.models.record.UnitOfMeasurement;
import energy.eddie.aiida.utils.ObisCode;

import java.nio.charset.StandardCharsets;

public class SmartGatewaysAdapterValueDeserializer {
    protected SmartGatewaysAdapterValueDeserializer() {}

    public static SmartGatewaysAdapterMessage deserialize(
            byte[] message
    ) {
        String[] lines = new String(message, StandardCharsets.UTF_8).split("\\r?\\n", -1);

        return new SmartGatewaysAdapterMessage(
                new SmartGatewaysMessageField("electricityEquipmentId",
                                              lines[0],
                                              UnitOfMeasurement.TEXT,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("gasEquipmentId", lines[1], UnitOfMeasurement.TEXT, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("electricityTariff", lines[2], UnitOfMeasurement.TEXT, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("electricityDeliveredTariff1",
                                              lines[3],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.POSITIVE_ACTIVE_ENERGY),
                new SmartGatewaysMessageField("electricityReturnedTariff1",
                                              lines[4],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.NEGATIVE_ACTIVE_ENERGY),
                new SmartGatewaysMessageField("electricityDeliveredTariff2",
                                              lines[5],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.POSITIVE_ACTIVE_ENERGY),
                new SmartGatewaysMessageField("electricityReturnedTariff2",
                                              lines[6],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.NEGATIVE_ACTIVE_ENERGY),
                new SmartGatewaysMessageField("reactiveEnergyDeliveredTariff1",
                                              lines[7],
                                              UnitOfMeasurement.KW,
                                              ObisCode.POSITIVE_REACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("reactiveEnergyReturnedTariff1",
                                              lines[8],
                                              UnitOfMeasurement.KW,
                                              ObisCode.NEGATIVE_REACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("reactiveEnergyDeliveredTariff2",
                                              lines[9],
                                              UnitOfMeasurement.KW,
                                              ObisCode.POSITIVE_REACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("reactiveEnergyReturnedTariff2",
                                              lines[10],
                                              UnitOfMeasurement.KW,
                                              ObisCode.NEGATIVE_REACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("powerCurrentlyDelivered",
                                              lines[11],
                                              UnitOfMeasurement.KW,
                                              ObisCode.POSITIVE_ACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("powerCurrentlyReturned",
                                              lines[12],
                                              UnitOfMeasurement.KW,
                                              ObisCode.NEGATIVE_ACTIVE_INSTANTANEOUS_POWER),
                new SmartGatewaysMessageField("phaseCurrentlyDeliveredL1",
                                              lines[13],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseCurrentlyDeliveredL2",
                                              lines[14],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseCurrentlyDeliveredL3",
                                              lines[15],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseCurrentlyReturnedL1",
                                              lines[16],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseCurrentlyReturnedL2",
                                              lines[17],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseCurrentlyReturnedL3",
                                              lines[18],
                                              UnitOfMeasurement.KWH,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseVoltageL1", lines[19], UnitOfMeasurement.VOLT, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseVoltageL2", lines[20], UnitOfMeasurement.VOLT, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phaseVoltageL3", lines[21], UnitOfMeasurement.VOLT, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phasePowerCurrentL1",
                                              lines[22],
                                              UnitOfMeasurement.AMPERE,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phasePowerCurrentL2",
                                              lines[23],
                                              UnitOfMeasurement.AMPERE,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("phasePowerCurrentL3",
                                              lines[24],
                                              UnitOfMeasurement.AMPERE,
                                              ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("gasDelivered", lines[25], UnitOfMeasurement.KWH, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("PowerDeliveredHour", lines[26], UnitOfMeasurement.KWH, ObisCode.UNKNOWN),
                new SmartGatewaysMessageField("GasDeliveredHour", lines[27], UnitOfMeasurement.KWH, ObisCode.UNKNOWN)
        );
    }
}
