package energy.eddie.regionconnector.at.api;


import energy.eddie.api.v0.process.model.PermissionRequest;

public interface AtPermissionRequest extends PermissionRequest {
    /**
     * The CM Request ID of this permission request.
     *
     * @return cmRequestId
     */
    String cmRequestId();

    /**
     * In austria every conversation with the permission administrator requires a conversation id.
     * For a permission request this id is generated by eddie.
     *
     * @return conversationId
     */
    String conversationId();
}
