package energy.eddie.regionconnector.at.api;


/**
 * A PermissionRequest represents the starting point of requesting the permission for data from an MDA.
 * It can have different states depending on where in the process of a specific Permission Administrator the request currently is.
 * This is the context class of the state pattern.
 *
 * @see <a href="https://refactoring.guru/design-patterns/state">State Pattern</link>
 */
public interface PermissionRequest {

    /**
     * The permissionId of a request.
     * It is used internally of the eddie framework to map permission requests or incoming consumption data
     *
     * @return permissionId
     */
    String permissionId();

    /**
     * The connectionId is an id that is given by the eligible party of the eddie framework.
     *
     * @return connectionId
     */
    String connectionId();

    /**
     * The CM Request ID of this permission request.
     *
     * @return cmRequestId
     */
    String cmRequestId();

    /**
     * In austria every conversation with the permission administrator requires a conversation id.
     * For a permission request this id is generated by eddie.
     *
     * @return conversationId
     */
    String conversationId();

    /**
     * The state of the permission request.
     *
     * @return the current state of the permission request.
     */
    PermissionRequestState state();

    /**
     * After a state transition was successful the permission requests state will be updated using this method.
     * Usually the old state will update this with the new state.
     *
     * @param state the new state of the PermissionRequest
     */
    void changeState(PermissionRequestState state);

    void validate() throws FutureStateException, PastStateException;

    void sendToPermissionAdministrator() throws FutureStateException, PastStateException;

    void receivedPermissionAdministratorResponse() throws FutureStateException, PastStateException;

    void terminate() throws FutureStateException, PastStateException;

    void accept() throws FutureStateException, PastStateException;

    void invalid() throws FutureStateException, PastStateException;

    void rejected() throws FutureStateException, PastStateException;
}
