# SPDX-FileCopyrightText: 2025 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
# SPDX-License-Identifier: Apache-2.0

name: Build Containers
description: Build and push EDDIE and AIIDA docker containers
inputs:
  version:
    description: 'version tag'
    required: true
  secrets:
    description: 'The github registry token'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Set up JDK
      uses: actions/setup-java@5d7b2146334bacf88728daaa70414a99f5164e0f
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Gradle build
      shell: bash
      run: ./gradlew installDist
    - name: "Docker build image: EDDIE"
      shell: bash
      run: docker build -f ./core/src/main/docker/Dockerfile -t eddie ./core
    - name: "Docker build image: EDDIE example-app"
      shell: bash
      run: docker build -f ./examples/example-app/src/main/docker/Dockerfile -t eddie-example-app ./examples/example-app
    - name: Print some debugging information
      shell: bash
      run: |
        echo github.repository_owner: ${{ github.repository_owner }}
        echo github.ref: ${{ github.ref }}
        echo GITHUB_RUN_ID: ${GITHUB_RUN_ID}
    # Usage of docker is done through direct commands instead of using predefined actions for these reasons:
    # - Usage of the docker command line is well documented and already understood by all developers that
    #   used docker before. Usage of a docker-related action requires additional knowledge that is seldomly present.
    # - Security tokens are not passed through an action to give less surface to supply chain attacks that might be
    #   used for stealing docker related secrets. That supply chain attack may occur in the used GitHub action or any
    #   library that is used by that action explicitly or implicitly. Especially in the Node.js/npm ecosystem that
    #   must be used by all GitHub actions, supply chain attacks became common in recent times.
    - name: ghcr.io login
      shell: bash
      env:
        SECRETS: ${{ inputs.secrets }}
      run: echo "$SECRETS" | docker login ghcr.io -u $ --password-stdin
    - name: "Docker push image: EDDIE example-app"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        IMAGE_NAME=eddie-example-app
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        echo IMAGE_NAME: $IMAGE_NAME
        echo IMAGE_ID: $IMAGE_ID
        echo VERSION: $VERSION
        docker tag ${IMAGE_NAME} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
    - name: "Docker push image: EDDIE"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        IMAGE_NAME=eddie
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        echo IMAGE_NAME: $IMAGE_NAME
        echo IMAGE_ID: $IMAGE_ID
        echo VERSION: $VERSION
        docker tag ${IMAGE_NAME} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
    - name: Post ghcr.io login
      shell: bash
      run: rm $HOME/.docker/config.json

    - name: Set up JDK 21
      uses: actions/setup-java@5d7b2146334bacf88728daaa70414a99f5164e0f
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and publish image
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        SECRETS: ${{ inputs.secrets }}
      run: |
        IMAGE_NAME=aiida
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        echo $IMAGE_ID
        ./gradlew --no-daemon jib --image $IMAGE_ID:$VERSION -Djib.to.auth.password=$SECRETS
