@startuml
title AIIDA E2E flow

actor Customer as C
participant "EDDIE Core" as EC
participant "MQTT Broker" as M
participant "AIIDA" as A

C -> EC: Click on "EDDIE connect button"\nand create permission request
EC -> EC: Produce CREATED, VALIDATED events
note over EC: Events are published to Kafka broker

EC -> C: Show QR code
EC -> EC: Produce SENT_TO_PA event

C -> A: Scan/Enter QR code to set up new permission

A -> A: Check if already a permission with\n<permissionId> from QR code exists

alt already exists
    A -> C: show error
else does not exist yet
    A -> EC: Make handshake HTTP request with permissionId
    EC -> EC: Produce HANDSHAKE_RECEIVED event
    EC -> A: Return data need details, start/end date

    A -> A: Check if permission request can\nbe fulfilled (e.g. requested data is available)
    alt cannot be fulfilled
        A -> C: Show cannot fulfill message
        A -> EC: Send UNABLE_TO_FULFILL status message (via HTTP)
    else can be fulfilled
        A -> C: Prompt for confirmation of data sharing

        C -> A: Confirm/Grant permission

        A -> EC: Second handshake (via HTTP) to request MQTT user & pw
        EC -> EC: Produce ACCEPTED event
        EC -> M: Create dedicated MQTT user & ACLs for AIIDA instance
        EC -> A: Return MQTT user & pw
        note across: If start date is far in the future, the MQTT credentials could be activated e.g. just a day before the start date.

        group Later, when permission start date is reached
            A -> M: Open connection
            A -> M: Subscribe to termination topic
            A -> M: Send data messages

            opt When end date is reached
            A -> M: Send FULFILLED status messages
            A -> A: Fulfill permission

            opt When customer revokes permission
            A -> M: Send REVOKED status messages
            A -> A: Revoke permission

            opt
            [-> EC: Received termination request from EP
            EC -> M: Send termination request\n(= permissionId on dedicated terminationTopic)
            M -> A: Forward termination request
            A -> A: Terminate permission

            note over EC, M: How to handle deletion of MQTT credentials?\nCannot do it right away, as AIIDA needs to receive termination.\nMaybe as a scheduled task, and if AIIDA does not honor the termination,\nit will be denied access when publishing via MQTT, and could act on that.
            note across: Is a TERMINATION_RECEIVED or TERMINATED status message from AIIDA to EDDIE required?
        end
    end
end
@enduml
