@startuml

rectangle "System Scope" {

    rectangle "Eligble Party Infrastructure" as ep_infrastructure {
        node "Eligible Party Website" as ep_website {
            [EDDIE Connect Button] as eddie_connect_button
            [EDDIE QR Code] as eddie_qr_code

            eddie_connect_button - eddie_qr_code : Generate QR code\nfor permission request
        }

        node "EDDIE Framework" as eddie {
            node "Eddie Core" as eddie_core {
              [AIIDA Region Connector] as eddie_aiida_rc
            }

            [Postgres DB] as eddie_db
            [EMXQ] as eddie_emqx

            () SQL as interface_eddie_db_emqx
            interface_eddie_db_emqx )- eddie_emqx : Authentication and\nAuthorization

            () SQL as interface_eddie_db_aiida_rc
            eddie_db - interface_eddie_db_emqx

            () SQL as interface_eddie_db_aiida_rc
            interface_eddie_db_aiida_rc -- eddie_db
            eddie_aiida_rc --( interface_eddie_db_aiida_rc

            () MQTT as interface_eddie_emqx_aiida_rc
            interface_eddie_emqx_aiida_rc )- eddie_aiida_rc
            eddie_emqx - interface_eddie_emqx_aiida_rc
        }

        eddie_aiida_rc - eddie_connect_button
    }

    rectangle "Final Customer Infrastructure" as fc_infrastructure {
        node "Final Customer's Smartphone" as fc_smartphone {
            [AIIDA Mobile Application] as aiida_mobile_app
        }

        node AIIDA as aiida {
            node "AIIDA Core" as aiida_core {
                [Data Source Adapter] as aiida_data_source
                [Streamer] as aiida_streamer

                aiida_data_source - aiida_streamer
            }
            [Timescale DB] as aiida_db
            [EMQX] as aiida_emqx

            () SQL as interface_aiida_db_emqx
            aiida_db - interface_aiida_db_emqx
            interface_aiida_db_emqx )- aiida_emqx : Authentication and\nAuthorization

            () SQL as interface_aiida_db_data_source
            aiida_data_source -( interface_aiida_db_data_source : Save data\nin DB
            interface_aiida_db_data_source -- aiida_db

            () MQTT as interface_aiida_emqx_data_source
            aiida_emqx -- interface_aiida_emqx_data_source
            aiida_data_source --( interface_aiida_emqx_data_source : Receive data\nfrom third party devices
        }

        aiida_core -- fc_smartphone : Accept permission request\nfrom EDDIE via QR code

        node "Final Customer's Data Source" as fc_data_source {
            [Third Party Device] as third_party_device
            [Data Source] as data_source

            data_source - third_party_device : Retrieve data from\nData Source
        }

        () MQTT as interface_aiida_emqx_third_party_device
        interface_aiida_emqx_third_party_device - aiida_emqx
        third_party_device --( interface_aiida_emqx_third_party_device: Send data to\nAIIDA via MQTT
    }

    eddie_qr_code - fc_smartphone  : Scan QR code\nfrom EDDIE

    () MQTT as interface_eddie_eqmx_aiida_streamer
    aiida_streamer -up-( interface_eddie_eqmx_aiida_streamer : Stream data to\nEP via MQTT
    eddie_emqx -- interface_eddie_eqmx_aiida_streamer
}
@enduml