package at.eda.xml.builders.customerconsent.cmnotification._01p11;

import at.ebutilities.schemata.customerconsent.cmnotification._01p11.ParamHistType;
import at.ebutilities.schemata.customerconsent.cmnotification._01p11.ResponseDataType;

import javax.annotation.Nullable;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * <p>Allows to create a ResponseDataType Object for CMNotification.
 * <p>Only the <b>responseCode</b> attribute is necessarily required according to the schema definition.
 *
 * @see ResponseDataType
 */
public class ResponseDataTypeBuilder {
    @Nullable
    private String consentId;
    @Nullable
    private String meteringPointId;
    @Nullable
    private List<Integer> responseCode;
    @Nullable
    private List<ParamHistType> paramHist;

    /**
     * Sets the unique ID generated by the distribution system operator, which identifies a data release
     *
     * @param consentId allowed object is
     *                  {@link String} max. 35 characters
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withConsentId(String consentId) {
        int LEN_CONSENT_ID = 35;
        if (consentId != null && consentId.length() > 35) {
            throw new IllegalArgumentException("`consentId` length cannot exceed " + LEN_CONSENT_ID + " characters.");
        }

        this.consentId = consentId;
        return this;
    }

    /**
     * Sets the metering point of the participant
     *
     * @param meteringPointId allowed object is
     *                        {@link String} max. 33 characters
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withMeteringPointId(String meteringPointId) {
        if (meteringPointId != null) {
            int LEN_METERING_POINT = 33;
            if (meteringPointId.length() > LEN_METERING_POINT) {
                throw new IllegalArgumentException("`meteringPointId` length cannot exceed " + LEN_METERING_POINT + " characters.");
            }

            String regex = "[0-9A-Za-z]*";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(meteringPointId);

            if (!matcher.matches()) {
                throw new IllegalArgumentException("`meteringPointId` does not match the necessary pattern (" + regex + ").");
            }
        }

        this.meteringPointId = meteringPointId;
        return this;
    }

    /**
     * Sets the response codes (1 – 999)
     *
     * @param responseCode allowed object is
     *                     {@link List<Integer>}
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withResponseCode(List<Integer> responseCode) {
        if (responseCode == null || responseCode.isEmpty()) {
            throw new IllegalArgumentException("`responseCode` cannot be empty.");
        }

        this.responseCode = responseCode;
        return this;
    }

    /**
     * Sets the deliverable historical periods with granularity
     *
     * @param paramHist allowed object is
     *                  {@link List<ParamHistType>}
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withParamHistory(List<ParamHistType> paramHist) {
        this.paramHist = paramHist;
        return this;
    }

    /**
     * Creates and returns a CMRequest Object
     *
     * @return {@link ResponseDataType}
     */
    public ResponseDataType build() {
        if (responseCode == null) {
            throw new IllegalStateException("Attribute `messageCode` is required.");
        }

        ResponseDataType responseData = new ResponseDataType();

        responseData.setConsentId(consentId);
        responseData.setMeteringPoint(meteringPointId);
        for (Integer responseCodeEntry : responseCode) {
            responseData.getResponseCode().add(responseCodeEntry);
        }
        if (paramHist != null) {
            for (ParamHistType paramHistEntry : paramHist) {
                responseData.getParamHist().add(paramHistEntry);
            }
        }

        return responseData;
    }
}
