package at.eda.xml.builders.customerconsent.cmnotification._01p11;

import at.ebutilities.schemata.customerconsent.cmnotification._01p11.ParamHistType;
import at.ebutilities.schemata.customerconsent.cmnotification._01p11.ResponseDataType;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Objects;

/**
 * <p>Allows to create a ResponseDataType Object for CMNotification.
 * <p>Only the <b>responseCode</b> attribute is necessarily required according to the schema definition.
 *
 * @see ResponseDataType
 */
public class ResponseDataTypeBuilder {
    private static final int LEN_CONSENT_ID = 35;
    private static final int LEN_METERING_POINT = 33;
    @Nullable
    private String consentId;
    @Nullable
    private String meteringPointId;
    @Nullable
    private List<Integer> responseCode;
    @Nullable
    private List<ParamHistType> paramHist;

    /**
     * Sets the unique ID generated by the distribution system operator, which identifies a data release
     *
     * @param consentId allowed object is
     *                  {@link String} max. 35 characters
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withConsentId(String consentId) {
        if (consentId != null && consentId.length() > 35) {
            throw new IllegalArgumentException("`consentId` length cannot exceed " + LEN_CONSENT_ID + " characters.");
        }

        this.consentId = consentId;
        return this;
    }

    /**
     * Sets the metering point of the participant
     *
     * @param meteringPointId allowed object is
     *                        {@link String} max. 33 characters
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withMeteringPointId(String meteringPointId) {
        if (meteringPointId != null) {
            if (meteringPointId.length() > LEN_METERING_POINT) {
                throw new IllegalArgumentException("`meteringPointId` length cannot exceed " + LEN_METERING_POINT + " characters.");
            }

            for (int i = 0; i < meteringPointId.length(); i++) {
                char ch = meteringPointId.charAt(i);
                if (!Character.isLetterOrDigit(ch)) {
                    throw new IllegalArgumentException("`meteringPointId` must consist only of letters and digits.");
                }
            }
        }

        this.meteringPointId = meteringPointId;
        return this;
    }

    /**
     * Sets the response codes (1 – 999)
     *
     * @param responseCode allowed object is
     *                     {@link List<Integer>}
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withResponseCode(List<Integer> responseCode) {
        if (Objects.requireNonNull(responseCode).isEmpty()) {
            throw new IllegalArgumentException("`responseCode` cannot be empty.");
        }

        this.responseCode = responseCode;
        return this;
    }

    /**
     * Sets the deliverable historical periods with granularity
     *
     * @param paramHist allowed object is
     *                  {@link List<ParamHistType>}
     * @return {@link ResponseDataTypeBuilder}
     */
    public ResponseDataTypeBuilder withParamHistory(List<ParamHistType> paramHist) {
        this.paramHist = paramHist;
        return this;
    }

    /**
     * Creates and returns a CMRequest Object
     *
     * @return {@link ResponseDataType}
     */
    public ResponseDataType build() {
        ResponseDataType responseData = new ResponseDataType();

        for (Integer responseCodeEntry : Objects.requireNonNull(responseCode, "Attribute `responseCode` is required.")) {
            responseData.getResponseCode().add(responseCodeEntry);
        }
        responseData.setConsentId(consentId);
        responseData.setMeteringPoint(meteringPointId);
        if (paramHist != null) {
            for (ParamHistType paramHistEntry : paramHist) {
                responseData.getParamHist().add(paramHistEntry);
            }
        }

        return responseData;
    }
}
