package energy.eddie.regionconnector.aiida.dtos;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.Set;

/**
 * This data transfer object contains all necessary information that should be encoded in a QR code, that is then
 * presented to the customer.
 *
 * @param permissionId         ID of this permission as generated by this region connector. AIIDA will use the same ID.
 * @param serviceName          Name of the service that the permission is for.
 * @param dataNeedId           ID of the dataNeed for this permission.
 * @param startDate            Start date from when on data should be shared with the EP.
 * @param expirationDate       Expiration date until which data should be shared.
 * @param connectionId         ConnectionId, that will be included in every message sent by AIIDA.
 * @param requestedCodes       Set of OBIS codes, that the EP wants to receive from the customer. If the customer's AIIDA system cannot provide <b>all</b> codes, the permission cannot be setup.
 * @param kafkaStreamingConfig Configuration for the streaming via Kafka.
 */
public record PermissionDto(
        @JsonProperty
        String permissionId,
        @JsonProperty
        String serviceName,
        @JsonProperty
        String dataNeedId,
        @JsonProperty
        LocalDate startDate,
        @JsonProperty
        LocalDate expirationDate,
        @JsonProperty
        String connectionId,
        @JsonProperty
        Set<String> requestedCodes,
        @JsonProperty
        KafkaStreamingConfig kafkaStreamingConfig) {
}
