package energy.eddie.api.v0_82.cim;

/**
 * Wrapper interface for market documents that adds EDDIE relevant data that are not part of the market document itself.
 *
 * @param <T> The type of the market document
 */
public interface EddieMarketDocument<T> {

    /**
     * The connectionId is an identifier that comes from the eligible party.
     * Its purpose is to enable the eligible party to identify all market documents that belong to the same connection.
     * A connection might be for example a user account.
     *
     * @return The connection ID of the market document
     */
    String connectionId();

    /**
     * The permissionId is an identifier generated by EDDIE.
     * A permissionId is generated for every permission request.
     * It can be used to identify all market documents that belong to the same permission.
     *
     * @return The permission ID of the market document
     */
    String permissionId();

    /**
     * The dataNeedId is an identifier associated with the data need used to create the permission.
     * When creating a permission, the data need is specified by the eligible party and decides which data is requested in what time frame.
     *
     * @return The data need ID of the market document
     */
    String dataNeedId();

    /**
     * The market document itself.
     * Most commonly this will be a CIM document.
     *
     * @return The market document
     */
    T marketDocument();
}
