package at.eda.xml.builders.customerconsent.cmrequest._01p10;

import at.ebutilities.schemata.customerconsent.cmrequest._01p10.ProcessDirectory;
import at.ebutilities.schemata.customerconsent.cmrequest._01p10.ReqType;
import at.eda.utils.CMRequestId;
import at.eda.xml.builders.customerprocesses.common.types._01p20.ProcessDirectorySBuilder;
import at.eda.xml.builders.helper.DateTimeConverter;

import javax.annotation.Nullable;
import java.time.LocalDate;
import java.util.Objects;

/**
 * <p>Allows to create a ProcessDirectory Object for CMRequest.
 * <p><b>messageId</b>, <b>conversationId</b>, <b>meteringPoint</b> and <b>consentId</b> are required according to the schema definition.
 *
 * @see ProcessDirectory
 * @see at.ebutilities.schemata.customerprocesses.common.types._01p20.ProcessDirectoryS
 */
public class ProcessDirectoryBuilder extends ProcessDirectorySBuilder {
    private static final int LEN_METERING_POINT = 33;
    private static final int LEN_CM_REQ_ID = 35;
    private static final int LEN_CONSENT_ID = 35;
    @Nullable
    private LocalDate processDate;
    @Nullable
    private String meteringPoint;
    @Nullable
    private String cmRequestId;
    @Nullable
    private String consentId;
    @Nullable
    private ReqType cmRequest;

    /**
     * Sets the globally unique message ID
     *
     * @param messageId allowed object is
     *                  {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    @Override
    public ProcessDirectoryBuilder withMessageId(String messageId) {
        super.withMessageId(messageId);
        return this;
    }

    /**
     * Sets the globally unique process ID
     *
     * @param conversationId allowed object is
     *                       {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    @Override
    public ProcessDirectoryBuilder withConversationId(String conversationId) {
        super.withConversationId(conversationId);
        return this;
    }

    /**
     * Sets the date of the process
     *
     * @param processDate allowed object is
     *                    {@link LocalDate}
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withProcessDate(LocalDate processDate) {
        this.processDate = processDate;
        return this;
    }

    /**
     * Sets the metering point of the participant
     *
     * @param meteringPoint allowed object is
     *                      {@link String} max. length 33
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withMeteringPoint(String meteringPoint) {
        if (Objects.requireNonNull(meteringPoint).isEmpty()) {
            throw new IllegalArgumentException("`meteringPoint` cannot be empty.");
        }

        if (meteringPoint.length() > LEN_METERING_POINT) {
            throw new IllegalArgumentException("`meteringPoint` length cannot exceed " + LEN_METERING_POINT + " characters.");
        }

        for (int i = 0; i < meteringPoint.length(); i++) {
            char ch = meteringPoint.charAt(i);
            if (!Character.isLetterOrDigit(ch)) {
                throw new IllegalArgumentException("`meteringPoint` must consist only of letters and digits.");
            }
        }

        this.meteringPoint = meteringPoint;
        return this;
    }

    /**
     * Sets the globally unique consent request ID (Assignment of a data release request to the end customer)
     *
     * @param cmRequestId allowed object is
     *                    {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withCMRequestId(String cmRequestId) {
        if (cmRequestId != null && cmRequestId.length() > LEN_CM_REQ_ID) {
            throw new IllegalArgumentException("`cmRequestId` length cannot exceed " + LEN_CM_REQ_ID + " characters.");
        }

        this.cmRequestId = cmRequestId;
        return this;
    }

    /**
     * Sets the consent ID (generated by the distribution system operator)
     *
     * @param consentId allowed object is
     *                  {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withConsentId(String consentId) {
        if (Objects.requireNonNull(consentId).isEmpty()) {
            throw new IllegalArgumentException("`consentId` cannot be empty.");
        }

        if (consentId.length() > LEN_CONSENT_ID) {
            throw new IllegalArgumentException("`consentId` length cannot exceed " + LEN_CONSENT_ID + " characters.");
        }

        this.consentId = consentId;
        return this;
    }

    /**
     * Sets the request details
     *
     * @param cmRequest allowed object is
     *                  {@link ReqType}
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withCMRequest(ReqType cmRequest) {
        this.cmRequest = cmRequest;
        return this;
    }

    /**
     * Creates and returns a ProcessDirectory Object
     *
     * @return {@link ProcessDirectory}
     */
    @Override
    public ProcessDirectory build() {
        ProcessDirectory processDir = new ProcessDirectory();

        processDir.setMessageId(Objects.requireNonNull(messageId, "Attributes `messageId` is required."));
        processDir.setConversationId(Objects.requireNonNull(conversationId, "Attributes `conversationId` is required."));
        processDir.setProcessDate(DateTimeConverter.dateToXml(Objects.requireNonNullElseGet(processDate, LocalDate::now)));
        processDir.setMeteringPoint(Objects.requireNonNull(meteringPoint, "Attribute `meteringPoint` is required."));
        processDir.setCMRequestId(Objects.requireNonNullElseGet(cmRequestId, () -> new CMRequestId(Objects.requireNonNull(messageId)).toString()));
        processDir.setConsentId(Objects.requireNonNull(consentId, "Attribute `consentId` is required."));
        processDir.setCMRequest(cmRequest);

        return processDir;
    }
}
