package at.eda.xml.builders.customerconsent.cmrequest._01p10;

import at.ebutilities.schemata.customerconsent.cmrequest._01p10.ProcessDirectory;
import at.ebutilities.schemata.customerconsent.cmrequest._01p10.ReqType;
import at.eda.xml.builders.customerprocesses.common.types._01p20.ProcessDirectorySBuilder;
import at.eda.xml.builders.helper.DateTimeConverter;

import javax.annotation.Nullable;
import java.time.LocalDate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * <p>Allows to create a ProcessDirectory Object for CMRequest.
 * <p><b>messageId</b>, <b>conversationId</b>, <b>meteringPoint</b> and <b>consentId</b> are required according to the schema definition.
 *
 * @see ProcessDirectory
 * @see at.ebutilities.schemata.customerprocesses.common.types._01p20.ProcessDirectoryS
 */
public class ProcessDirectoryBuilder extends ProcessDirectorySBuilder {
    @Nullable
    private LocalDate processDate;
    private String meteringPoint = "";
    @Nullable
    private String cmRequestId;
    private String consentId = "";
    @Nullable
    private ReqType cmRequest;

    /**
     * Sets the globally unique message ID
     *
     * @param messageId allowed object is
     *                  {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    @Override
    public ProcessDirectoryBuilder withMessageId(String messageId) {
        super.withMessageId(messageId);
        return this;
    }

    /**
     * Sets the globally unique process ID
     *
     * @param conversationId allowed object is
     *                       {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    @Override
    public ProcessDirectoryBuilder withConversationId(String conversationId) {
        super.withConversationId(conversationId);
        return this;
    }

    /**
     * Sets the date of the process
     *
     * @param processDate allowed object is
     *                    {@link LocalDate}
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withProcessDate(LocalDate processDate) {
        this.processDate = processDate;
        return this;
    }

    /**
     * Sets the metering point of the participant
     *
     * @param meteringPoint allowed object is
     *                      {@link String} max. length 33
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withMeteringPoint(String meteringPoint) {
        if (meteringPoint == null || meteringPoint.length() == 0) {
            throw new IllegalArgumentException("`meteringPoint` cannot be empty.");
        }

        int LEN_METERING_POINT = 33;
        if (meteringPoint.length() > LEN_METERING_POINT) {
            throw new IllegalArgumentException("`meteringPoint` length cannot exceed " + LEN_METERING_POINT + " characters.");
        }

        String regex = "[0-9A-Za-z]*";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(meteringPoint);

        if (!matcher.matches()) {
            throw new IllegalArgumentException("`meteringPoint` does not match the necessary pattern (" + regex + ").");
        }

        this.meteringPoint = meteringPoint;
        return this;
    }

    /**
     * Sets the globally unique consent request ID (Assignment of a data release request to the end customer)
     *
     * @param cmRequestId allowed object is
     *                    {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withCMRequestId(String cmRequestId) {
        int LEN_CM_REQ_ID = 35;
        if (cmRequestId != null && cmRequestId.length() > LEN_CM_REQ_ID) {
            throw new IllegalArgumentException("`cmRequestId` length cannot exceed " + LEN_CM_REQ_ID + " characters.");
        }

        this.cmRequestId = cmRequestId;
        return this;
    }

    /**
     * Sets the consent ID (generated by the distribution system operator)
     *
     * @param consentId allowed object is
     *                  {@link String} max. length 35
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withConsentId(String consentId) {
        if (consentId == null || consentId.length() == 0) {
            throw new IllegalArgumentException("`consentId` cannot be empty.");
        }

        int LEN_CONSENT_ID = 35;
        if (consentId.length() > LEN_CONSENT_ID) {
            throw new IllegalArgumentException("`consentId` length cannot exceed " + LEN_CONSENT_ID + " characters.");
        }

        this.consentId = consentId;
        return this;
    }

    /**
     * Sets the request details
     *
     * @param cmRequest allowed object is
     *                  {@link ReqType}
     * @return {@link ProcessDirectoryBuilder}
     */
    public ProcessDirectoryBuilder withCMRequest(ReqType cmRequest) {
        this.cmRequest = cmRequest;
        return this;
    }

    /**
     * Creates and returns a ProcessDirectory Object
     *
     * @return {@link ProcessDirectory}
     */
    @Override
    public ProcessDirectory build() {
        super.build();

        if (meteringPoint.length() == 0 || consentId.length() == 0) {
            throw new IllegalStateException("Attributes `messageId`, `conversationId`, `meteringPoint` and `consentId` are required.");
        }

        ProcessDirectory processDir = new ProcessDirectory();

        processDir.setConversationId(conversationId);
        processDir.setMessageId(messageId);
        if (processDate != null) {
            processDir.setProcessDate(DateTimeConverter.dateToXMl(processDate));
        }
        processDir.setMeteringPoint(meteringPoint);
        processDir.setCMRequestId(cmRequestId);
        processDir.setConsentId(consentId);
        processDir.setCMRequest(cmRequest);

        return processDir;
    }
}
