### GET ID and name of all data needs
GET http://localhost:8080/data-needs/api


### GET details of a data need
@id = 9bd0668f-cc19-40a8-99db-dc2cb2802b17
GET http://localhost:8080/data-needs/api/{{id}}

### GET details of multiple data needs
GET http://localhost:8080/data-needs/api/?data-need-id={{id}}
