package energy.eddie.aiida.model.permission;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;

import java.time.Instant;
import java.util.Objects;
import java.util.Set;

@Entity
public class Permission {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Nullable
    @Column(nullable = false, name = "permission_id")
    private String permissionId;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PermissionStatus status;
    @Column(nullable = false)
    private String serviceName;
    @Column(nullable = false)
    private Instant startTime;
    @Column(nullable = false)
    private Instant expirationTime;
    @Column(nullable = false)
    private Instant grantTime;
    @Nullable
    private Instant terminateTime = null;
    @Column(nullable = false)
    private String connectionId;
    @Column(nullable = false)
    @ElementCollection(fetch = FetchType.EAGER)
    @NotEmpty(message = "At least one OBIS code needs to be requested.")
    private Set<String> requestedCodes;
    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "kafka_streaming_config_id", referencedColumnName = "id")
    private KafkaStreamingConfig kafkaStreamingConfig;


    /**
     * To be called after the customer has granted a new permission.
     * Creates a new permission object with the status ACCEPTED.
     * If near real-time is requested, the resolution has to be 0 and the AggregationMethod NONE.
     * The streamingInterval has to be greater or equal to the resolution.
     * If the streamingInterval is greater than the resolution, multiple data points will be sent in batches.
     *
     * @param serviceName          Display name of the service for which this permission is granted.
     * @param startTime            The UTC start timestamp for this permission.
     * @param expirationTime       UTC timestamp when this permission expires and no more data should be shared.
     * @param grantTime            Timestamp when the user granted the permission.
     * @param connectionId         ID generated by the EDDIE framework and that AIIDA sends along with every message to the framework.
     * @param requestedCodes       Codes object containing which codes shall be shared with the EP.
     * @param kafkaStreamingConfig StreamingInfo object containing configuration how data shall be shared.
     */
    public Permission(String serviceName, Instant startTime, Instant expirationTime, Instant grantTime, String connectionId, Set<String> requestedCodes, KafkaStreamingConfig kafkaStreamingConfig) {
        this.serviceName = Objects.requireNonNull(serviceName);
        this.startTime = Objects.requireNonNull(startTime);
        this.expirationTime = Objects.requireNonNull(expirationTime);
        this.grantTime = Objects.requireNonNull(grantTime);
        this.connectionId = Objects.requireNonNull(connectionId);
        this.requestedCodes = Objects.requireNonNull(requestedCodes);
        this.kafkaStreamingConfig = Objects.requireNonNull(kafkaStreamingConfig);

        this.status = PermissionStatus.ACCEPTED;
    }

    /**
     * Constructor only for JPA.
     */
    @SuppressWarnings("NullAway.Init")
    protected Permission() {
    }

    /**
     * Returns the UUID of this permission.
     * The UUID is generated by the database and therefore null until the permission is persisted by the JPA.
     */
    @Nullable
    public String permissionId() {
        return permissionId;
    }

    /**
     * Returns the UTC start timestamp for sharing data of this permission.
     */
    public Instant startTime() {
        return startTime;
    }

    /**
     * Returns the UTC timestamp when this permission expires and no more data should be shared.
     */
    public Instant expirationTime() {
        return expirationTime;
    }

    /**
     * Returns the UTC timestamp when the customer granted the permission.
     * Will return null until the customer grants the permission.
     */
    public Instant grantTime() {
        return grantTime;
    }

    /**
     * Sets the grantTime to the specified time.
     */
    public void grantTime(Instant grantTime) {
        this.grantTime = Objects.requireNonNull(grantTime);
    }

    /**
     * Returns the UTC timestamp when the customer either rejected the permission during the permission setup,
     * or when the customer terminated the permission.
     * The status field provides information about whether this field represents the rejection or the termination timestamp.
     *
     * @return The rejection or termination timestamp.
     */
    @Nullable
    public Instant terminateTime() {
        return terminateTime;
    }

    /**
     * Set the UTC timestamp when the customer either rejected the permission during the permission setup,
     * or when the customer terminated the permission.
     *
     * @param terminateTime The rejection or termination timestamp.
     */
    public void terminateTime(Instant terminateTime) {
        this.terminateTime = Objects.requireNonNull(terminateTime);
    }

    /**
     * Returns the connectionId that was generated by the EDDIE framework and is sent along with each message to the EP.
     */
    public String connectionId() {
        return connectionId;
    }

    /**
     * Returns the service name for which this permission is for.
     */
    public String serviceName() {
        return serviceName;
    }

    /**
     * Returns the current status of the permission.
     */
    public PermissionStatus status() {
        return status;
    }

    /**
     * Returns the KafkaStreamingConfig object that holds the configuration for the streaming protocol.
     */
    public KafkaStreamingConfig streamingInfo() {
        return kafkaStreamingConfig;
    }
}
