package energy.eddie.aiida.model.permission;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import energy.eddie.aiida.constraints.ExpirationTimeAfterStartTime;
import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

import java.time.Instant;
import java.util.Set;

import static java.util.Objects.requireNonNull;

@Entity
@Table(name = "permission")
@ExpirationTimeAfterStartTime
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Permission {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Nullable
    @Column(nullable = false, name = "permission_id")
    @JsonProperty
    private String permissionId;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @JsonProperty
    private PermissionStatus status;
    @Column(nullable = false)
    @NotBlank(message = "serviceName mustn't be null or blank.")
    @JsonProperty(required = true)
    private String serviceName;
    @Column(nullable = false)
    @NotNull(message = "startTime mustn't be null.")
    @JsonProperty(required = true)
    private Instant startTime;
    @Column(nullable = false)
    @NotNull(message = "expirationTime mustn't be null.")
    @JsonProperty(required = true)
    private Instant expirationTime;
    @Column(nullable = false)
    @NotNull(message = "grantTime mustn't be null.")
    @JsonProperty(required = true)
    private Instant grantTime;
    @Nullable
    @JsonProperty
    private Instant terminateTime = null;
    @Column(nullable = false)
    @NotBlank(message = "connectionId mustn't be null or blank.")
    @JsonProperty(required = true)
    private String connectionId;
    @Column(nullable = false)
    @ElementCollection(fetch = FetchType.EAGER)
    @NotEmpty(message = "At least one OBIS code needs to be requested.")
    @JsonProperty(required = true)
    private Set<String> requestedCodes;
    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "kafka_streaming_config_id", referencedColumnName = "id")
    @Valid  // if Permission is validated, also validate kafkaStreamingConfig
    @JsonProperty(required = true)
    private KafkaStreamingConfig kafkaStreamingConfig;


    /**
     * To be called after the customer has granted a new permission.
     * Creates a new permission object with the status ACCEPTED.
     * If near real-time is requested, the resolution has to be 0 and the AggregationMethod NONE.
     * The streamingInterval has to be greater or equal to the resolution.
     * If the streamingInterval is greater than the resolution, multiple data points will be sent in batches.
     *
     * @param serviceName          Display name of the service for which this permission is granted.
     * @param startTime            The UTC start timestamp for this permission.
     * @param expirationTime       UTC timestamp when this permission expires and no more data should be shared.
     * @param grantTime            Timestamp when the user granted the permission.
     * @param connectionId         ID generated by the EDDIE framework and that AIIDA sends along with every message to the framework.
     * @param requestedCodes       Codes object containing which codes shall be shared with the EP.
     * @param kafkaStreamingConfig StreamingInfo object containing configuration how data shall be shared.
     */
    public Permission(String serviceName, Instant startTime, Instant expirationTime, Instant grantTime, String connectionId, Set<String> requestedCodes, KafkaStreamingConfig kafkaStreamingConfig) {
        this.serviceName = requireNonNull(serviceName);
        this.startTime = requireNonNull(startTime);
        this.expirationTime = requireNonNull(expirationTime);
        this.grantTime = requireNonNull(grantTime);
        this.connectionId = requireNonNull(connectionId);
        this.requestedCodes = requireNonNull(requestedCodes);
        this.kafkaStreamingConfig = requireNonNull(kafkaStreamingConfig);

        this.status = PermissionStatus.ACCEPTED;
    }

    /**
     * Constructor only for JPA.
     */
    @SuppressWarnings("NullAway.Init")
    protected Permission() {
    }

    /**
     * Returns the UUID of this permission.
     * The UUID is generated by the database and therefore null until the permission is persisted by the JPA.
     */
    @Nullable
    public String permissionId() {
        return permissionId;
    }

    /**
     * Returns the UTC start timestamp for sharing data of this permission.
     */
    public Instant startTime() {
        return startTime;
    }

    /**
     * Returns the UTC timestamp when this permission expires and no more data should be shared.
     */
    public Instant expirationTime() {
        return expirationTime;
    }

    /**
     * Returns the UTC timestamp when the customer granted the permission.
     * Will return null until the customer grants the permission.
     */
    public Instant grantTime() {
        return grantTime;
    }

    /**
     * Returns the time at which either the EP terminated the permission or the customer revoked the permission.
     * The return value of {@link #status()} indicates which of the two cases occurred.
     */
    @Nullable
    public Instant terminateTime() {
        return terminateTime;
    }

    /**
     * Set the UTC timestamp when either the EP terminated the permission or the customer revoked the permission.
     * Use {@link #updateStatus(PermissionStatus)} to indicate which of the two cases occurred.
     *
     * @param terminateTime The rejection or termination timestamp.
     */
    public void terminateTime(Instant terminateTime) {
        requireNonNull(terminateTime);

        if (terminateTime.isBefore(grantTime))
            throw new IllegalArgumentException("terminateTime mustn't be before grantTime.");

        this.terminateTime = terminateTime;
    }

    /**
     * Returns the connectionId that was generated by the EDDIE framework and is sent along with each message to the EP.
     */
    public String connectionId() {
        return connectionId;
    }

    /**
     * Returns the Set of OBIS codes that the EP wants to receive.
     */
    public Set<String> requestedCodes() {
        return requestedCodes;
    }

    /**
     * Returns the service name for which this permission is for.
     */
    public String serviceName() {
        return serviceName;
    }

    /**
     * Returns the current status of the permission.
     */
    public PermissionStatus status() {
        return status;
    }

    /**
     * Updates the status of this permission to <i>newStatus</i>.
     *
     * @param newStatus New status for this permission.
     */
    public void updateStatus(PermissionStatus newStatus) {
        this.status = requireNonNull(newStatus);
    }

    /**
     * Returns the KafkaStreamingConfig object that holds the configuration for the streaming protocol.
     */
    public KafkaStreamingConfig kafkaStreamingConfig() {
        return kafkaStreamingConfig;
    }
}
