openapi: 3.1.0
info:
  title: CDS
  description: https://customerdata.carbondataspec.org
  version: 0.0.0
servers:
  - url: https://{cds-server}
    variables:
      cds-server:
        default: cds.utilityapi.com
tags:
  - name: Server Metadata
    description: |
      This specification defines how utilities and other entities may provide structured “metadata”, such as reference information about them, functionality they offer, and how organizations can interoperate with them. The defined base metadata endpoint is intended to act as a starting point for organizations to discover details and capabilities of energy utilities and other similar entities.
    externalDocs:
      url: https://daniel-utilityapi.github.io/Connectivity/specs/cdsc-wg1-01/
  - name: Client Registration
    description: |
      This specification defines how utilities and other central entities (“Servers”) may allow third parties (“Clients”) to register, configure, and maintain connectivity with the utility or other central entity. This specification mostly extends various OAuth specifications (Dynamic Client Registration, Authorization Server Metadata, and more) to create a robust framework for offering secure, streamlined, and standardized connectivity between utilities and third parties.
    externalDocs:
      url: https://daniel-utilityapi.github.io/Connectivity/specs/cdsc-wg1-02/
  - name: Customer Data
    description: |
      This specification defines how utilities and other central entities (“Servers”) may allow third parties (“Clients”) to access utility account holder data (“Customer Data”), including for use cases that require account holders to authorize the access. This specification extends CDSC-WG1-02 (Client Registration) to add OAuth authorization scopes for Customer Data, as well as defining the APIs used to access Customer Data when authorization is granted.
    externalDocs:
      url: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg3-01/
paths:
  /.well-known/carbon-data-spec.json:
    get:
      operationId: Carbon Data Spec
      description: |
        If the Server wishes to provide metadata publicly, the Server MUST support a metadata endpoint at the Well-Known URI "/.well-known/carbon-data-spec.json" on their hostname (e.g. https://example.com/.well-known/carbon-data-spec.json). 
        Servers MAY additionally support other public and restricted URLs for special case or private metadata endpoints, as needed.
      tags:
        - Server Metadata
      responses:
        200:
          description: CDS Metadata response
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/CDSMetadata"
  /api/cds/v1/coverages/:
    get:
      operationId: Coverages
      description: |
        If Servers include the coverage Server capability, a URL to the utility or entity’s coverage MUST be included in the metadata object.
        When the URL is requested using the HTTP GET method and the request is valid, the Server MUST respond with a “200 OK” Status Code and body containing JSON object formatted according to the Coverage Listing Format.
        Cache-optimized responses, such as “304 Not Modified”, to Client requests with cached value headers, such as If-None-Match, is also acceptable.
        For invalid requests and error responses, Servers MUST respond with the appropriate Response Code for the type of issue or error (e.g. “503 Service Unavailable” if the Server is temporarily down for maintenance).
      tags:
        - Server Metadata
      parameters:
        - in: query
          name: ids
          required: false
          schema:
            type: string
            example: "123e4567-e89b-12d3-a456-426614174000 123e4567-e89b-12d3-a456-426614174001"

      responses:
        200:
          description: |
            Returns the supported Coverages of the server.
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/CoverageListing"
        304:
          description: Can be used when content has not been modified.
        404:
          description: Used when server does not include coverage in capabilities.
        503:
          description: Used when server is down for maintenance.

  /.well-known/oauth-authorization-server:
    get:
      operationId: OAuth Authorization Server
      description: |
      tags:
        - Client Registration
      responses:
        200:
          description: OAuth Metadata, containing URIs to endpoints to create an oauth client
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/OAuthMetadata"

  /oauth/register/:
    post:
      operationId: OAuth Client Registration
      description: |
        This specification requires Clients and Servers follow the process described in OAuth’s Client Registration Request, with the following modifications. 
        
        - Clients MAY submit additional named values that are defined as part of scope registration_requirements and registration_optional arrays in cds_scope_descriptions objects, using the registration field reference’s field_name value as the submitted key in the registration request.
        
        See https://daniel-utilityapi.github.io/Connectivity/specs/cdsc-wg1-02/#client-registration-process
      tags:
        - Client Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "cds-schemas.json/#/$defs/ClientRegistrationRequest"
      responses:
        200:
          description: OAuth Client has been successfully created
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/ClientRegistrationResponse"

  /api/accounts:
    get:
      operationId: Accounts Endpoint
      description: |
        This specification requires Servers provide a set of Application Programming Interfaces (APIs) allowing Clients to retrieve a Customer’s Account details for which they are authorized to access. These APIs are authenticated using a Bearer access_token granted that provisions access for a scope that allows access to the Accounts API.
      externalDocs:
        url: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg3-01/#accounts-api
      tags:
        - Customer Data
      parameters:
        - name: "cds_account_ids"
          in: query
          description: "A space-separated list of cds_account_id values for which the Servers MUST filter the Accounts."
          required: false
          schema:
            type: string
            example: "123 456 789"

        - name: "customer_numbers"
          in: query
          description: "A space-separated list of customer_number values for which the Servers MUST filter the Accounts. Customer number values of null MUST be treated as invalid for this URL parameter filter."
          required: false
          schema:
            type: string
            example: "1001 1002"

        - name: "account_numbers"
          in: query
          description: "A space-separated list of account_number values for which the Servers MUST filter the Accounts."
          required: false
          schema:
            type: string
            example: "A001 A002 A003"

        - name: "q"
          in: query
          description: |
            A search term for which the Servers MUST filter the Accounts following fields for values that case-insensitive contains the search term.
            Fields that may be searched by the query term include:
            - cds_account_id
            - customer_number
            - account_number
            - account_address
            - account_name
          required: false
          schema:
            type: string
            example: "John Doe"
      responses:
        200:
          description: |
            Listings of Account objects MUST be ordered in reverse chronological order by cds_modified timestamp, where the most recently updated relevant Account MUST be first in each listing.
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/Accounts"

  /api/usagesegments:
    get:
      operationId: Usage Segment Endpoint
      externalDocs:
        url: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg3-01/overview#usage-segment-api
      description: |
        This specification requires Servers provide a set of APIs allowing Clients to retrieve a Customer’s and Server’s Usage Segment objects for which they are authorized to access. These APIs are authenticated using a Bearer access_token granted that provisions access for a scope that allows access to the Usage Segments API.
      tags:
        - Customer Data
      parameters:
        - name: cds_usagesegment_ids
          in: query
          description: A space-separated list of cds_usagesegment_id values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "usage_segment_id_1 usage_segment_id_2"
        - name: before
          in: query
          description: An ISO8601 datetime for which the Server MUST filter the Usage Segment object segment_start to values that are on or before this date.
          required: false
          schema:
            type: string
            format: date-time
            example: "2023-01-01T00:00:00Z"
        - name: after
          in: query
          description: An ISO8601 datetime for which the Server MUST filter the Usage Segment object segment_end to values that are on or after this date.
          required: false
          schema:
            type: string
            format: date-time
            example: "2023-02-01T00:00:00Z"
        - name: cds_account_ids
          in: query
          description: A space-separated list of cds_account_id values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "account_id_1 account_id_2"
        - name: account_numbers
          in: query
          description: A space-separated list of account_number values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "12345 67890"
        - name: cds_servicecontract_ids
          in: query
          description: A space-separated list of cds_servicecontract_id values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "servicecontract_id_1 servicecontract_id_2"
        - name: contract_numbers
          in: query
          description: A space-separated list of contract_number values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "contract_001 contract_002"
        - name: cds_servicepoint_ids
          in: query
          description: A space-separated list of cds_servicepoint_id values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "servicepoint_id_1 servicepoint_id_2"
        - name: servicepoint_numbers
          in: query
          description: A space-separated list of servicepoint_number values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "servicepoint_123 servicepoint_456"
        - name: cds_meterdevice_ids
          in: query
          description: A space-separated list of cds_meterdevice_ids values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "meterdevice_id_1 meterdevice_id_2"
        - name: meter_numbers
          in: query
          description: A space-separated list of meter_numbers values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "meter_001 meter_002"
        - name: cds_billsection_ids
          in: query
          description: A space-separated list of cds_billsection_id values for which the Servers MUST filter the Usage Segments.
          required: false
          schema:
            type: string
            example: "billsection_id_1 billsection_id_2"
      responses:
        200:
          description: |
            Listings of Usage Segments MUST be ordered in alphanumeric order by aggregation_number. In situations where relevant Usage Segments have the same aggregation_number, those Usage Segments with the same aggregation_number are further ordered in alphanumeric order by account_number. In situations where relevant Usage Segments have the same account_number, those Usage Segments with the same account_number are further ordered in alphanumeric order by contract_number. In situations where relevant Usage Segments have the same contract_number, those Usage Segments with the same contract_number are further ordered in chronological order by segment_start, where the relevant Usage Segment object with the earliest date is listed first. In situations where relevant Usage Segments have the same segment_start, those Usage Segments with the same segment_start are further ordered in reverse chronological order by cds_modified, where the most recently updated relevant Usage Segment object is listed first.
          content:
            application/json:
              schema:
                $ref: "cds-schemas.json/#/$defs/UsageSegments"