name: SFTP d
description: Build and push EDDIE and AIIDA docker containers
inputs:
  source:
    required: true
    description: "The source directory of the files that should be deployed to the SFTP server"
  destination:
    required: true
    description: "The destination directory on the SFTP server"
  host:
    required: true
    description: "Host of the SFTP server"
  login_name:
    required: true
    description: "Login name of the SFTP server user"
  private_key:
    required: true
    description: "Private key for the SFTP server"
  keyfile:
    required: false
    description: "Filepath for private key"
    default: "./sftp_key"
  batchfile:
    required: false
    description: "Filepath for private key"
    default: "./batchfile"
runs:
  using: composite
  steps:
    - name: Get keys
      shell: bash
      run: |
        echo "${{ inputs.private_key }}" > ${{ inputs.keyfile }}
        chmod 400 ${{ inputs.keyfile }}
    - name: Create batchfile
      shell: bash
      run: |
        echo "mkdir ${{ inputs.destination }}" > ${{ inputs.batchfile }}
        echo "put -r ${{ inputs.source }} ${{ inputs.destination }}" >> ${{ inputs.batchfile }}
    - name: See batchfile
      shell: bash
      run: |
        cat ${{ inputs.batchfile }}
    - name: Deploy files to SFTP server
      shell: bash
      run: |
        sftp -i ${{ inputs.keyfile }} -b ${{ inputs.batchfile }} ${{ inputs.login_name}}@${{ inputs.host }}
    - name: Clean up
      if: always()
      shell: bash
      run: |
        rm  ${{ inputs.sftp_key }} ${{ inputs.batchfile }}