package energy.eddie.aiida.models.permission;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Nullable;
import jakarta.persistence.*;

import java.time.Instant;
import java.util.Set;

import static java.util.Objects.requireNonNull;

@Entity
@Table(name = "permission")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Permission {
    @Schema(description = "Unique ID of this permission.", requiredMode = Schema.RequiredMode.REQUIRED, example = "a4dc1bad-b9fe-47ae-9336-690cfb4aada9")
    @Id
    @Column(nullable = false, name = "permission_id", columnDefinition = "bpchar", length = 36)
    @JsonProperty
    private String permissionId;
    @Schema(description = "Status of this permission.", requiredMode = Schema.RequiredMode.REQUIRED, example = "ACCEPTED")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @JsonProperty
    private PermissionStatus status;
    @Schema(description = "Name of the EP service that requested near real-time data.", example = "My Energy Visualization Service")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private String serviceName;
    @Schema(description = "ID of the data need for which this permission was created.", example = "MY_DATA_NEED_23")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private String dataNeedId;
    @Schema(description = "ISO8601 timestamp when the data sharing should start.", example = "2023-10-01T08:00:00.000Z")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private Instant startTime;
    @Schema(description = "ISO8601 timestamp when the data sharing should automatically stop. Must be after startTime.", example = "2023-10-31T20:00:00.000Z")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private Instant expirationTime;
    @Schema(description = "ISO8601 timestamp when the customer granted the sharing permission.", example = "2023-10-01T08:00:00.000Z")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private Instant grantTime;
    @Schema(description = "ISO8601 timestamp when the permission was revoked or terminated. See status for the exact reason.", example = "2023-10-20T08:00:00.000Z")
    @JsonProperty
    @Nullable
    private Instant revokeTime = null;
    @Schema(description = "Connection ID as supplied by EDDIE/EP.", example = "SomeRandomString")
    @Column(nullable = false)
    @JsonProperty(required = true)
    private String connectionId;
    @Schema(description = "Set of OBIS codes that the EP wants to receive.", type = "array", implementation = String.class, example = "[\"1-0:1.8.0\", \"1-0:1.7.0\"]")
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "permission_requested_codes", joinColumns = @JoinColumn(name = "permission_id"))
    @Column(name = "code", nullable = false)
    @JsonProperty(required = true)
    private Set<String> requestedCodes;


    /**
     * To be called after the customer has granted a new permission.
     * Creates a new permission object with the status ACCEPTED.
     * If near real-time is requested, the resolution has to be 0 and the AggregationMethod NONE.
     * The streamingInterval has to be greater or equal to the resolution.
     * If the streamingInterval is greater than the resolution, multiple data points will be sent in batches.
     *
     * @param permissionId         UUID of this permission, as generated by the AIIDA region-connector.
     * @param serviceName          Display name of the service for which this permission is granted.
     * @param dataNeedId           ID of the data need for which this permission was created.
     * @param startTime            The UTC start timestamp for this permission.
     * @param expirationTime       UTC timestamp when this permission expires and no more data should be shared.
     * @param grantTime            Timestamp when the user granted the permission.
     * @param connectionId         ID generated by the EDDIE framework and that AIIDA sends along with every message to the framework.
     * @param requestedCodes       Codes object containing which codes shall be shared with the EP.
     */
    public Permission(
            String permissionId,
            String serviceName,
            String dataNeedId,
            Instant startTime,
            Instant expirationTime,
            Instant grantTime,
            String connectionId,
            Set<String> requestedCodes
    ) {
        this.permissionId = permissionId;
        this.serviceName = serviceName;
        this.dataNeedId = dataNeedId;
        this.startTime = startTime;
        this.expirationTime = expirationTime;
        this.grantTime = grantTime;
        this.connectionId = connectionId;
        this.requestedCodes = requestedCodes;

        this.status = PermissionStatus.ACCEPTED;
    }

    /**
     * Constructor only for JPA.
     */
    @SuppressWarnings("NullAway.Init")
    protected Permission() {
    }

    /**
     * Returns the UUID of this permission.
     */
    public String permissionId() {
        return permissionId;
    }

    /**
     * Returns the UTC start timestamp for sharing data of this permission.
     */
    public Instant startTime() {
        return startTime;
    }

    /**
     * Returns the UTC timestamp when this permission expires and no more data should be shared.
     */
    public Instant expirationTime() {
        return expirationTime;
    }

    /**
     * Returns the UTC timestamp when the customer granted the permission.
     * Will return null until the customer grants the permission.
     */
    public Instant grantTime() {
        return grantTime;
    }

    /**
     * Returns the time at which either the EP terminated the permission or the customer revoked the permission.
     * The return value of {@link #status()} indicates which of the two cases occurred.
     */
    @Nullable
    public Instant revokeTime() {
        return revokeTime;
    }

    /**
     * Set the UTC timestamp when either the EP terminated the permission or the customer revoked the permission.
     * Use {@link #updateStatus(PermissionStatus)} to indicate which of the two cases occurred.
     *
     * @param revokeTime The revocation or termination timestamp.
     */
    public void revokeTime(Instant revokeTime) {
        requireNonNull(revokeTime);

        if (revokeTime.isBefore(grantTime))
            throw new IllegalArgumentException("revokeTime must not be before grantTime.");

        this.revokeTime = revokeTime;
    }

    /**
     * Returns the connectionId that was generated by the EDDIE framework and is sent along with each message to the EP.
     */
    public String connectionId() {
        return connectionId;
    }

    /**
     * Returns the Set of OBIS codes that the EP wants to receive.
     */
    public Set<String> requestedCodes() {
        return requestedCodes;
    }

    /**
     * Returns the service name for which this permission is for.
     */
    public String serviceName() {
        return serviceName;
    }

    /**
     * Returns the ID of the data need for which this permission was created.
     */
    public String dataNeedId() {
        return dataNeedId;
    }

    /**
     * Returns the current status of the permission.
     */
    public PermissionStatus status() {
        return status;
    }

    /**
     * Updates the status of this permission to <i>newStatus</i>.
     *
     * @param newStatus New status for this permission.
     */
    public void updateStatus(PermissionStatus newStatus) {
        this.status = requireNonNull(newStatus);
    }
}
