name: Build release docker images

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    # Required when the tag is pushed via GitHub, since GitHub will not execute actions based on pushes, if they happen in a workflow, see: https://docs.github.com/en/actions/concepts/security/github_token#when-github_token-triggers-workflow-runs
    workflows:
      - "tag-release.yml"
    types:
      - completed

jobs:
  tag-release:
    runs-on: [ Linux ]
    outputs:
      release_body: ${{ steps.create-changelog.outputs.content }}
      version: ${{ steps.create-changelog.outputs.version }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          fetch-depth: 0

      - name: Create changelog
        id: create-changelog
        uses: orhun/git-cliff-action@07dda386992489f0a6151dee53f3a137713644de
        with:
          args: -v --latest --no-exec --github-repo ${{ github.repository }}
      - name: Print version
        run: |
          echo Version: ${{ steps.create-changelog.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: ${{ steps.create-changelog.outputs.version }}
          body: ${{ steps.create-changelog.outputs.content }}
          make_latest: true
  build:
    runs-on: [ Linux ]
    permissions:
      contents: read
      packages: write
    env:
      registry: ghcr.io/eddie-energy
    needs: tag-release
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Print version
        run: |
          echo Version: ${{ needs.tag-release.outputs.version }}
      - name: Build docker containers
        uses: ./.github/actions/build-containers
        with:
          version: ${{ needs.tag-release.outputs.version }}
          secrets: ${{ secrets.GITHUB_TOKEN }}
