package energy.eddie.aiida.dtos;

import com.fasterxml.jackson.annotation.JsonProperty;
import energy.eddie.aiida.constraints.ExpirationTimeAfterStartTime;
import energy.eddie.aiida.models.permission.KafkaStreamingConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import org.hibernate.validator.constraints.UUID;

import java.time.Instant;
import java.util.Set;

/**
 * This data transfer object is expected by the permission API endpoint to set up a new permission.
 * All parameters are required.
 *
 * @param permissionId         UUID of this permission, as generated by the AIIDA region-connector.
 * @param serviceName          Name of the service that the permission is for.
 * @param startTime            UTC start timestamp, from when on data should be shared with the EP.
 * @param expirationTime       UTC timestamp until which data should be shared.
 * @param grantTime            UTC timestamp when the customer granted the permission.
 * @param connectionId         UUID string, that should be sent along with every message related to the requested permission.
 * @param requestedCodes       Set of OBIS codes, that the EP wants to receive from the customer. If the customer's AIIDA system cannot provide <b>all</b> codes, the permission cannot be setup.
 * @param kafkaStreamingConfig Configuration for the streaming via Kafka.
 */
@ExpirationTimeAfterStartTime
public record PermissionDto(
        @Schema(description = "UUID of this permission as generated by the AIIDA region-connector.", example = "f69f9bc2-e16c-4de4-8c3e-00d219dcd819")
        @NotNull(message = "must not be null.")
        @UUID(message = "must be an UUID with 36 characters.")
        @JsonProperty(required = true)
        String permissionId,
        @Schema(description = "Name of the EP service that requested near real-time data.", example = "My Energy Visualization Service")
        @NotBlank(message = "must not be null or blank.")
        @JsonProperty(required = true)
        String serviceName,
        @Schema(description = "ID of the data need for which this permission was created.", example = "MY_DATA_NEED_23")
        @NotBlank(message = "must not be null or blank.")
        @JsonProperty(required = true)
        String dataNeedId,
        @Schema(description = "ISO8601 timestamp when the data sharing should start.", example = "2023-10-01T08:00:00.000Z")
        @NotNull(message = "must not be null.")
        @JsonProperty(required = true)
        Instant startTime,
        @Schema(description = "ISO8601 timestamp when the data sharing should automatically stop. Must be after startTime.", example = "2023-10-31T20:00:00.000Z")
        @NotNull(message = "must not be null.")
        @JsonProperty(required = true)
        Instant expirationTime,
        @Schema(description = "ISO8601 timestamp when the customer granted the sharing permission.", example = "2023-10-01T08:00:00.000Z")
        @NotNull(message = "must not be null.")
        @JsonProperty(required = true)
        Instant grantTime,
        @Schema(description = "Connection ID as supplied by EDDIE/EP.", example = "SomeRandomString")
        @NotBlank(message = "must not be null or blank.")
        @JsonProperty(required = true)
        String connectionId,
        @Schema(description = "Set of OBIS codes that the EP wants to receive. All requested codes must be available at this AIIDA instance, otherwise the permission cannot be accepted.", type = "array", implementation = String.class, example = "[\"1-0:1.8.0\", \"1-0:1.7.0\"]")
        @NotEmpty(message = "At least one OBIS code needs to be requested.")
        @JsonProperty(required = true)
        Set<String> requestedCodes,
        @Valid  // if PermissionDto is validated, also validate kafkaStreamingConfig
        @JsonProperty(required = true)
        @NotNull(message = "must not be null.")
        KafkaStreamingConfig kafkaStreamingConfig) {
}
